// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kunrrnlmffkzmmcumcsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1bnJybmxtZmZrem1tY3VtY3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNzIwOTQsImV4cCI6MjA2MDg0ODA5NH0.ToGs1CSlO9vWADqRca6kjzdyV6ctTIL6uEiWkjsmLf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);